In [ ]:
#1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.

In [24]:
import numpy as np
arr_zeros = np.zeros([1,10,1],dtype = int)
arr_zeros = np.append(arr_zeros, arr_zeros[0])
arr_zeros = np.insert(arr_zeros,4,1)
print(arr_zeros)

[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [32]:
#2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h. 
import numpy as np
arr_h = np.arange(10,25,1)
arr_hs = np.flip(arr_h)
print(arr_h)
print(arr_hs)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
#3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác 0. 
import numpy as np

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
filter_arr = []
for element in arr_k:
    if element > 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
arr_l = arr_k[filter_arr]

print("arr_l =",arr_l)

#4. Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.
arr_n = np.append(arr_l, [10,20])
print("arr_l cap nhat =",arr_n)

#5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.
arr_m =np.insert(arr_n,4,100)
print("arr_m =",arr_m)

#6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.
filter_array = []
for element in arr_m:
    if element > 2:
        filter_array.append(True)
    else:
        filter_array.append(False)
arr_h = arr_m[filter_array]

print("arr_h =",arr_h)


arr_l = [1 2 8 2 1 3 5]
arr_l cap nhat = [ 1  2  8  2  1  3  5 10 20]
arr_m = [  1   2   8   2 100   1   3   5  10  20]
arr_h = [  8 100   3   5  10  20]
