In [6]:
#1. Tạo array arr có kích thước 3x3 với các giá trị True
import numpy as np
arr = np.array([[0,1,0],[1,1,1],[0,1,0]])
arr = np.full((3, 3), True)

print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [17]:
#2. Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). 
#Tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D 
#Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại. 
import numpy as np
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape((3, 3))
print(arr_2D)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại. 

In [ ]:
#4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.

In [ ]:
#5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.

In [ ]:
#6. Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), 
#Kiểm tra trong array có giá trị rỗng không? 

In [ ]:
#7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.